version: '3.7'

services:

  mysql:
    image: mysql:8.0.26
    container_name: ${PROJECT_NAME}.mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_ROOT_PASSWORD: ${PROJECT_ROOT}
      MYSQL_USER: ${PROJECT_USR}
      MYSQL_PASSWORD: ${PROJECT_PSR}
    volumes:
      - mysql-volume:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}.nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d

  php:
    restart: unless-stopped
    container_name: ${PROJECT_NAME}.php
    build:
      context: ${PWD}
      dockerfile: ./docker/php/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}.redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql-volume:
